FILES=src/*.py test/*.py
TESTFILES=test/*.py

all:
	@make test

lint:
	@( echo "lint me..." )

test:
	@( echo "test me..." )
	@( make lint )

watch:
	@( ./watcher.js )


.PHONY:	lint
.PHONY:	watch
.PHONY:	test
